### ISSUE TITLE
Missing `handle` in Jetstream crashes

### ISSUE THREAD

**Issue by CanYumusak** [christiandeange/ozone#13]
After listening to the Jetstream firehose for a while the stream crashed due to the missing `handle` property in a JSON.

Stacktrace:

```
kotlinx.serialization.MissingFieldException: Field 'handle' is required for type with serial name 'app.bsky.jetstream.SubscribeIdentity', but it was missing at path: $.identity
	at kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeSerializableValue(StreamingJsonDecoder.kt:95)
	at kotlinx.serialization.encoding.AbstractDecoder.decodeSerializableValue(AbstractDecoder.kt:43)
	at kotlinx.serialization.encoding.AbstractDecoder.decodeNullableSerializableElement(AbstractDecoder.kt:78)
	at app.bsky.jetstream.SubscribeEvent$$serializer.deserialize(subscribeEvent.kt:10)
	at app.bsky.jetstream.SubscribeEvent$$serializer.deserialize(subscribeEvent.kt:10)
	at kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeSerializableValue(StreamingJsonDecoder.kt:69)
	at kotlinx.serialization.json.Json.decodeFromString(Json.kt:165)
	at sh.christian.ozone.jetstream.JetstreamApi$messages$$inlined$map$1$2.emit(Emitters.kt:51)
	at sh.christian.ozone.jetstream.JetstreamApi$messages$$inlined$mapNotNull$1$2.emit(Emitters.kt:63)
	at kotlinx.coroutines.flow.FlowKt__ChannelsKt.emitAllImpl$FlowKt__ChannelsKt(Channels.kt:33)
	at kotlinx.coroutines.flow.FlowKt__ChannelsKt.access$emitAllImpl$FlowKt__ChannelsKt(Channels.kt:1)
	at kotlinx.coroutines.flow.FlowKt__ChannelsKt$emitAllImpl$1.invokeSuspend(Channels.kt)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:101)
	at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:263)
	at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:95)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:69)
	at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:47)
	at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source)
	at dev.yumusak.MainKt.main(Main.kt:65)
	at dev.yumusak.MainKt.main(Main.kt)
Caused by: kotlinx.serialization.MissingFieldException: Field 'handle' is required for type with serial name 'app.bsky.jetstream.SubscribeIdentity', but it was missing
	at kotlinx.serialization.internal.PluginExceptionsKt.throwMissingFieldException(PluginExceptions.kt:20)
	at app.bsky.jetstream.SubscribeIdentity.<init>(subscribeIdentity.kt:12)
	at app.bsky.jetstream.SubscribeIdentity.<init>(subscribeIdentity.kt)
	at app.bsky.jetstream.SubscribeIdentity$$serializer.deserialize(subscribeIdentity.kt:12)
	at app.bsky.jetstream.SubscribeIdentity$$serializer.deserialize(subscribeIdentity.kt:12)
	at kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeSerializableValue(StreamingJsonDecoder.kt:69)
	... 21 more

```

**Comment by christiandeange** [comment]
Oops yeah, looks like it is not marked as required in the [upstream lexicon](https://github.com/bluesky-social/atproto/blob/c72145dbeb2d67068bc28c00a13447e0d382d121/lexicons/com/atproto/sync/subscribeRepos.json#L118). Will be fixed in an upcoming release.

**Comment by CanYumusak** [comment]
Isn't it the other way round? It's not required and is missing from the payload

**Comment by christiandeange** [comment]
That's according to the AT Protocol spec I linked above, yes. It's allowed to be missing from the payload. But my homemade jetstream lexicon accidentally says the handle is required, which is a bug. I'll have to update it to align with the upstream spec.

**Comment by CanYumusak** [comment]
Ah! Makes sense, thanks for clarifying
